MainFolder/site-alo-mundo/MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from MeuApp import views # Isso nao conflita com sites com mais aplicacoes?
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="homepage"),
    path("SegundaPagina", views.segundaPagina, name="segunda"),
    path("contatos/", include("contatos.urls")),
]

MainFolder/site-alo-mundo/MeuSite/contatos/urls.py
from django.urls import path
from contatos import views

app_name = "contatos"

urlpatterns = [
    path("lista/", views.ContatoListView.as_view(), name="lista-contatos"),   
    path("cria/", views.ContatoCreateView.as_view(), name="cria-contato"),
    path("atualiza/<int:pk>/", views.ContatoUpdateView.as_view(), name="atualiza"),
    path("deleta/<int:pk>/", views.ContatoDeleteView.as_view(), name="deleta"),
]

MainFolder/site-alo-mundo/MeuSite/MeuApp/models.py
from django.db import models

# Create your models here.

MainFolder/site-alo-mundo/MeuSite/contatos/models.py
from django.db import models

class Pessoa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, help_text="Entre o nome")
    idade = models.IntegerField(help_text="Entre a idade")
    salario = models.DecimalField(max_digits=8, decimal_places=2, help_text="Entre o salário")
    email = models.EmailField(help_text="Entre o email", max_length=254)
    telefone = models.CharField(max_length=20, help_text="Entre o telefone com DDD e DDI")
    dtNasc = models.DateField(help_text="Nascimento no formato DD/MM/AAAA", verbose_name="Data de Nascimento")

    def __str__(self):
        return self.nome

MainFolder/site-alo-mundo/MeuSite/contatos/forms.py
from django import forms
from contatos.models import Pessoa

class ContatoModel2Form(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = "__all__"

MainFolder/site-alo-mundo/MeuSite/MeuApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,"MeuApp/home.html")

def segundaPagina(request):
    return render(request,"MeuApp/segundaPagina.html")

MainFolder/site-alo-mundo/MeuSite/contatos/views.py
from django.shortcuts import render
from django.views.generic.base import View
from contatos.models import Pessoa
from contatos.forms import ContatoModel2Form
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
# Create your views here.

class ContatoListView(View):

    def get(self, request, *args, **kwargs):
        pessoas = Pessoa.objects.all()
        contexto = {"pessoas": pessoas}
        return render(request, "contatos/listaContatos.html", contexto)


class ContatoDeleteView(View):

    def get(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        contexto = {'pessoa': pessoa}
        return render(request, "contatos/confirmaExclusao.html", contexto)

class ContatoUpdateView(View):

    def get(self,request,pk,*args,**kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        contexto = {'form': ContatoModel2Form(instance=pessoa)}
        return render(request, "contatos/atualizaContato.html", contexto)
    
    def post(self,request,pk,*args,**kwargs):
        pessoa = get_object_or_404(Pessoa, pk=pk)
        formulario = ContatoModel2Form(request.POST, instance=pessoa)
        if formulario.is_valid():
            pessoa = formulario.save()
            pessoa.save()
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            contexto = {'form': formulario}
            return render(request, "contatos/atualizaContato.html", contexto)


class ContatoCreateView(View):

    def get(self, request, *args, **kwargs):
        contexto = {'form': ContatoModel2Form()}
        return render(request, "contatos/cadastroContato.html", contexto)
    
    def post(self, request, *args, **kwargs):
        formulario = ContatoModel2Form(request.POST)
        if formulario.is_valid():
            formulario.save()
            contexto = {
                'form': ContatoModel2Form,
                'mensagem': "Contato cadastrado com sucesso!"
            }
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            contexto = {
                'form': formulario,
                'mensagem': "Erro ao cadastrar contato!"
            }
            return render(request, "contatos/cadastroContato.html", contexto)

MainFolder/site-alo-mundo/MeuSite/MeuApp/templates/MeuApp/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home Page</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h1>Home Page</h1>
    <h2>Meu Primeiro Site Django</h2>
    <form action="{% url 'segunda'%}">
        <input type="submit" value="Envia dados">
    </form>
</body>
</html>

MainFolder/site-alo-mundo/MeuSite/MeuApp/templates/MeuApp/segundaPagina.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Segunda Pagina</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='segundaPagina.js'></script>
</head>
<body>
    <h1>Segunda Página</h1>
    <h2>Minha 2a Página</h2>
    <p>
        <a href="{% url 'homepage'%}">Volta</a>
    </p>
</body>
</html>

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/atualizaContato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Contato</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Atualiza Contato</h1>
    <form method="post">
        {% csrf_token %}
        <table class="formulario">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</body>
</html>

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/cadastroContato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Contato</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Cadastro de Contato</h1>
    <form method="post">
        {% csrf_token %}
        <table class="formulario">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</body>
</html>

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/confirmaExclusao.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Contato</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Confirmação de Exclusão</h1>
    <p>Você tem certeza que deseja excluir o contato "{{ pessoa.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a href="{% url 'contatos:lista-contatos' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</body>
</html>

        <button type="submit" class="btn btn-danger">Deletar</button>
    </form>
</body>
</html>

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/header.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/links.html
<a href="/" class="btn btn-primary"> Home Page </a>
<a href="{% url 'contatos:lista-contatos' %}" class="btn btn-primary"> Lista de Contatos </a>
<a href="{% url 'contatos:cria-contato' %}" class="btn btn-primary"> Cadastrar Contato </a>

MainFolder/site-alo-mundo/MeuSite/contatos/templates/contatos/listaContatos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pessoas</title>
    <link rel="stylesheet" href="{% static 'contatos/css/styles.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Lista de Pessoas</h1>
    <table border="0" class="m-1">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa in pessoas %}
            <tr>
                <td>{{ pessoa.nome }}</td>
                <td>{{ pessoa.email }}</td>
                <td>{{ pessoa.telefone }}</td>
                <td><a href="{% url 'contatos:atualiza' pk=pessoa.id %}" class="btn btn-info">Editar</a> 
                    / Excluir</td>
            </tr>
            {% empty %}
                <tr>
                    <td colspan="4">Nenhuma pessoa encontrada.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>